### ISSUE TITLE
[Documentation]: Improve paging audit test readme to provide accurate and complete usage details 

### ISSUE THREAD

**Issue by spbrogan** [Microsoft/mu_plus#365]
### Request Description

The paging audit test app readme seems way out of date and with the introduction of new tests and "modes" to run the app in it needs docs to clearly explain.  

### Are you going to make the change?

Someone else needs to make the change

### Do you need maintainer feedback?

No maintainer feedback needed

**Comment by TaylorBeebe** [comment]
https://github.com/microsoft/mu_plus/pull/459 addresses this issue

**Comment by TaylorBeebe** [comment]
https://github.com/microsoft/mu_plus/pull/459 has been committed. Closing this issue
