### ISSUE TITLE
[Bug]: The MfciPolicy.py does not work with -d and -a parameter

### ISSUE THREAD

**Issue by MarcChen46** [Microsoft/mu_plus#597]
### Is there an existing issue for this?

- [x] I have searched existing issues

### Current Behavior

When we tried the MfciPolicy.py with -a or -d parameter, it will failed at the SetUefiVar function, below is the error message for reference.

![Image](https://github.com/user-attachments/assets/117f9419-9fe0-4b7b-86f4-90e3aa76889a)

### Expected Behavior

The MfciPolicy.py should be able to apply or delete Mfci related variables via SetUefiVar function

### Steps To Reproduce

1. boot to OS
2. perform "python MfciPolicy.py -a <token>" or "python MfciPolicy.py -d"

### Build Environment

- OS(s): Windows
- Tool Chain(s): VS2022
- Targets Impacted: RELEASE, DEBUG

### Version Information

v2024050001.0.0

### Urgency

Medium

### Are you going to fix this?

Someone else needs to fix it

### Do you need maintainer feedback?

No maintainer feedback needed

### Anything else?

@apop5

**Comment by apop5** [comment]
Fixed in #601
